// packages/xstate-react/src/fsm.ts
import isDevelopment from '#is-development';
import {
  createMachine,
  interpret,
  InterpreterStatus,
  MachineImplementationsFrom,
  ServiceFrom,
  StateFrom,
  StateMachine
} from '@xstate/fsm';
import { useCallback, useEffect, useRef, useState } from 'react';
import useIsomorphicLayoutEffect from 'use-isomorphic-layout-effect';
import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector';
import useConstant from './useConstant';

function identity<T>(a: T): T {
  return a;
}

export function useMachine<TMachine extends StateMachine.AnyMachine>(
  stateMachine: TMachine,
  options?: MachineImplementationsFrom<TMachine>
): [StateFrom<TMachine>, ServiceFrom<TMachine>['send'], ServiceFrom<TMachine>] {
  const persistedStateRef = useRef<StateMachine.AnyState>();

  if (isDevelopment) {
    const [initialMachine] = useState(stateMachine);

    if (stateMachine !== initialMachine) {
      console.warn(
        'Machine given to `useMachine` has changed between renders. This is not supported and might lead to unexpected results.\n' +
        'Please make sure that you pass the same Machine as argument each time.'
      );
    }
  }

  const [service, queue] = useConstant(() => {
    const queue: unknown[] = [];
    const service = interpret(
      createMachine(
        stateMachine.config,
        options ? options : (stateMachine as any)._options
      )
    );
    const { send } = service;
    service.send = (event) => {
      if (service.status === InterpreterStatus.NotStarted) {
        queue.push(event);
        return;
      }
      send(event);
      persistedStateRef.current = service.state;
    };
    return [service, queue];
  });

  // TODO: consider using `useInsertionEffect` if available
  useIsomorphicLayoutEffect(() => {
    if (options) {
      (service as any)._machine._options = options;
    }
  });

  const useServiceResult = useService(service);

  useEffect(() => {
    service.start(persistedStateRef.current);
    queue.forEach(service.send);

    persistedStateRef.current = service.state;

    return () => {
      service.stop();
    };
  }, []);

  return useServiceResult as any;
}

const isEqual = (
  _prevState: StateMachine.AnyState,
  nextState: StateMachine.AnyState
) => nextState.changed === false;

export function useService<TService extends StateMachine.AnyService>(
  service: TService
): [StateFrom<TService>, TService['send'], TService] {
  const getSnapshot = useCallback(() => service.state, [service]);

  const subscribe = useCallback(
    (handleStoreChange) => {
      const { unsubscribe } = service.subscribe(handleStoreChange);
      return unsubscribe;
    },
    [service]
  );

  const storeSnapshot = useSyncExternalStoreWithSelector(
    subscribe,
    getSnapshot,
    getSnapshot,
    identity,
    isEqual
  );

  return [storeSnapshot, service.send, service] as any;
}

// packages/xstate-solid/src/fsm.ts
import type {
  MachineImplementationsFrom,
  ServiceFrom,
  StateFrom,
  StateMachine
} from '@xstate/fsm';
import { createMachine, interpret } from '@xstate/fsm';
import type { Accessor } from 'solid-js';
import { createMemo, onCleanup, createEffect } from 'solid-js';
import { createImmutable } from './createImmutable';
import { isServer } from 'solid-js/web';
import { unwrap } from 'solid-js/store';

type UseFSMServiceReturn<TService extends StateMachine.AnyService> = [
  StateFrom<TService>,
  TService['send']
];

type UseFSMMachineReturn<TService extends StateMachine.AnyService> = [
  ...UseFSMServiceReturn<TService>,
  TService
];

export function useMachine<TMachine extends StateMachine.AnyMachine>(
  machine: TMachine,
  options?: MachineImplementationsFrom<TMachine>
): UseFSMMachineReturn<ServiceFrom<TMachine>> {
  const resolvedMachine = createMachine(
    machine.config,
    options ? options : (machine as any)._options
  );

  const service = interpret(resolvedMachine);

  if (!isServer) {
    service.start();
    onCleanup(() => service.stop());
  }

  const [state, send] = useService(service);
  return [state, send, service] as UseFSMMachineReturn<ServiceFrom<TMachine>>;
}

export function useService<TService extends StateMachine.AnyService>(
  service: TService | Accessor<TService>
): UseFSMServiceReturn<TService> {
  const serviceMemo = createMemo(() =>
    typeof service === 'function' ? service() : service
  );

  const [state, setState] = createImmutable(
    deriveFSMState(serviceMemo().state as StateFrom<TService>)
  );

  const setNewState = (currentState: StateFrom<TService>) => {
    setState(deriveFSMState(currentState, unwrap(state)));
  };

  createEffect(() => {
    const currentService = serviceMemo();
    // this eager `setState` here is important because the state could change between render and effect's call
    // however, it might also create some extra work that might not be necessary
    // perhaps we should only do this if the state has changed
    // we'd have to track the "original" state to check if the current one is different from it
    // (for that purpose we can't use the derived one created by `createImmutable` as that's a copy of the original)
    setNewState(currentService.state as StateFrom<TService>);
    const { unsubscribe } = currentService.subscribe(setNewState);
    onCleanup(unsubscribe);
    return false;
  });

  const send: TService['send'] = (event) => serviceMemo().send(event);

  return [state, send];
}

function deriveFSMState<State extends StateMachine.AnyState>(
  state: State,
  prevState?: State
): State {
  return {
    ...state,
    matches:
      prevState && prevState.value === state.value
        ? prevState.matches
        : state.matches
  } as typeof state;
}
